# Ширина окон приложения.
WIDTH_MAIN_WINDOW = 850
WIDTH_DATABASE_WINDOW = 800

# Ширина для виджетов.
WIDTH_PARAMETERS_WIDGET = 400
WIDTH_ACTION_WIDGET = 400
WIDTH_DATA_WIDGET = 400
WIDTH_RESULT_WIDGET = 400
WIDTH_CONTROL_WIDGET = 200

# Ширина для кнопок.
WIDTH_PUSH_BUTTON_CLEAR = 150
WIDTH_PUSH_BUTTON_RESULT = 150
WIDTH_PUSH_BUTTON_SAVE = 150
WIDTH_PUSH_BUTTON_EXIT = 150
WIDTH_PUSH_BUTTON_EDIT_DATABASE = 40
WIDTH_PUSH_BUTTON_MATERIAL = 37
WIDTH_PUSH_BUTTON_TYPE_PART = 37
WIDTH_PUSH_BUTTON_PATTERN = 37
WIDTH_PUSH_BUTTON_SETTINGS = 37
WIDTH_PUSH_BUTTON_DATABASE_EXIT = 37
WIDTH_PUSH_BUTTON_ADD_DATA = 35
WIDTH_PUSH_BUTTON_DELETE_DATA = 35
WIDTH_PUSH_BUTTON_SAVE_DATA = 35

# Ширина для комбинированных кнопок.
WIDTH_COMBO_BOX_MATERIAL = 230
WIDTH_COMBO_BOX_BRAND = 230
WIDTH_COMBO_BOX_TYPE_PART = 230

# Высота окон приложения.
HEIGHT_MAIN_WINDOW = 600
HEIGHT_DATABASE_WINDOW = 600

# Высота для виджетов.
HEIGHT_PARAMETERS_WIDGET = 220
HEIGHT_ACTION_WIDGET = 90
HEIGHT_DATA_WIDGET = 220
HEIGHT_RESULT_WIDGET = 220
HEIGHT_CONTROL_WIDGET = 250

# Высота для кнопок.
HEIGHT_PUSH_BUTTON_CLEAR = 30
HEIGHT_PUSH_BUTTON_RESULT = 30
HEIGHT_PUSH_BUTTON_SAVE = 30
HEIGHT_PUSH_BUTTON_EXIT = 30
HEIGHT_PUSH_EDIT_DATABASE = 30
HEIGHT_PUSH_EDIT_MATERIAL = 35
HEIGHT_PUSH_EDIT_TYPE_PART = 35
HEIGHT_PUSH_EDIT_PATTERN = 35
HEIGHT_PUSH_EDIT_SETTINGS = 35
HEIGHT_PUSH_EDIT_DATABASE_EXIT = 35
HEIGHT_PUSH_BUTTON_ADD_DATA = 30
HEIGHT_PUSH_BUTTON_DELETE_DATA = 30
HEIGHT_PUSH_BUTTON_SAVE_DATA = 30

# Высота для комбинированных кнопок.
HEIGHT_COMBO_BOX_MATERIAL = 30
HEIGHT_COMBO_BOX_BRAND = 30
HEIGHT_COMBO_BOX_TYPE_PART = 30
