# Ширина для виджетов.
WIDTH_PARAMETERS_WIDGET = 450
WIDTH_ACTION_WIDGET = 450
WIDTH_DATA_WIDGET = 450
WIDTH_RESULT_WIDGET = 450

# Высота для виджетов.
HEIGHT_PARAMETERS_WIDGET = 220
HEIGHT_ACTION_WIDGET = 90
HEIGHT_DATA_WIDGET = 220
HEIGHT_RESULT_WIDGET = 220

# TODO: добавить размеры для остальных элементов
