# Object name
NAME_WIDGET = "widget"
NAME_PUSH_BUTTON = "pushButton"
NAME_LINE_EDIT = "lineEdit"
NAME_LABEL = "label"
NAME_COMBO_BOX = "comboBox"
NAME_TEXT_EDIT = "textEdit"
NAME_TABLE_WIDGET = "tableWidget"

# Size
WIDTH_WIDGET = 400
HEIGHT_ACTION_WIDGET = 90
HEIGHT_PARAMETERS_WIDGET = 220
WIDTH_PUSH_BUTTON = 150
HEIGHT_PUSH_BUTTON = 30
WIDTH_PUSH_BUTTON_WITH_IMAGE = 37
HEIGHT_PUSH_BUTTON_WITH_IMAGE = 35
WIDTH_COMBO_BOX = 200
HEIGHT_COMBO_BOX = 30
WIDTH_LINE_EDIT = 200
HEIGHT_LINE_EDIT = 30
WIDTH_CONTROL_WIDGET = 200
HEIGHT_CONTROL_WIDGET = 250
